server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-vehiculos
          uri: lb://ms-orders:8090
          predicates:
            - Path=/api/register/**
        - id: ms-products
          uri: lb://ms-products:8091
          predicates:
            - Path=/products/**