version: "3.8"
services:
  postgres-db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hola123
      POSTGRES_DB: AutoFix
    ports:
      - 5432:5432
  app:
    container_name: autofix
    image: zthfelipe/autofix-proyect
    ports:
      - 8090:8090
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/AutoFix?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=hola123
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db
